DB_URL=postgresql://root:secret@localhost:5433/expense_tracker?sslmode=disable

postgres:
	docker run --name postgres --network bank-network -p 5433:5432 -e POSTGRES_USER=user -e POSTGRES_PASSWORD=secret -d postgres

createdb:
	docker exec -it postgres createdb --username=user --owner=user expense_tracker

dropdb:
	docker exec -it postgres dropdb expense_tracker

migrateup:
	migrate -path db/migration -database "$(DB_URL)" -verbose up

migratedown:
	migrate -path db/migration -database "$(DB_URL)" -verbose down

sqlc:
	sqlc generate

.PHONY: postgres createdb dropdb migrateup migratedown sqlc