// Code generated by sqlc. DO NOT EDIT.
// source: incomes.sql

package db

import (
	"context"
	"database/sql"
)

const createIncomes = `-- name: CreateIncomes :one
INSERT INTO incomes (
    description, amount, category_id
) VALUES (
    $1, $2, $3
)
RETURNING id, description, amount, category_id, created_at
`

type CreateIncomesParams struct {
	Description sql.NullString `json:"description"`
	Amount      int64          `json:"amount"`
	CategoryID  int64          `json:"category_id"`
}

func (q *Queries) CreateIncomes(ctx context.Context, arg CreateIncomesParams) (Income, error) {
	row := q.db.QueryRowContext(ctx, createIncomes, arg.Description, arg.Amount, arg.CategoryID)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIncomes = `-- name: DeleteIncomes :exec
DELETE FROM incomes
WHERE id = $1
`

func (q *Queries) DeleteIncomes(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIncomes, id)
	return err
}

const getIncomes = `-- name: GetIncomes :one
SELECT id, description, amount, category_id, created_at FROM incomes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIncomes(ctx context.Context, id int64) (Income, error) {
	row := q.db.QueryRowContext(ctx, getIncomes, id)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listIncomes = `-- name: ListIncomes :many
SELECT id, description, amount, category_id, created_at FROM incomes
ORDER BY created_at
`

func (q *Queries) ListIncomes(ctx context.Context) ([]Income, error) {
	rows, err := q.db.QueryContext(ctx, listIncomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.CategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncomes = `-- name: UpdateIncomes :exec
UPDATE incomes
    set description = $2,
    amount = $3,
    category_id = $4
WHERE id = $1
`

type UpdateIncomesParams struct {
	ID          int64          `json:"id"`
	Description sql.NullString `json:"description"`
	Amount      int64          `json:"amount"`
	CategoryID  int64          `json:"category_id"`
}

func (q *Queries) UpdateIncomes(ctx context.Context, arg UpdateIncomesParams) error {
	_, err := q.db.ExecContext(ctx, updateIncomes,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.CategoryID,
	)
	return err
}
