// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	IsForIncomes bool      `json:"is_for_incomes"`
	CreatedAt    time.Time `json:"created_at"`
}

type Entry struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	Amount      int64     `json:"amount"`
	CategoryID  uuid.UUID `json:"category_id"`
	TypeID      uuid.UUID `json:"type_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type EntryType struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
